cmake_url: https://github.com/Kitware/CMake/releases/download/v3.25.2/cmake-3.25.2-linux-x86_64.sh
gcc_version: 12
llvm_gpg: https://apt.llvm.org/llvm-snapshot.gpg.key
llvm_repo: http://apt.llvm.org/{{ ansible_distribution_release }}/
llvm_version: 15
